# VooDoo Plugin Master Config
CutClean: false #Disables all of the below. Change to true to turn it on
  FromPigs: false #False = Disable all of the pig related cooked porkchop drops
    pigmax: 2 # Max amount of cooked pork to give out
    pigmin: 0 # Min. amount of cooked pork to give out
    pigXPmax: 4 #Max. XP to give out for killing pig
    pigXPmin: 10 #Min. XP to give out for killing pig
  FromCows: false
    Cowsmax: 2
    Cowsmin: 0
    CowsXPmax: 10
    CowsXPmin: 4
  FromChicken: false
    Chickenmax: 2
    Chickenmin: 0
    ChickenXPmax: 10
    ChickenXPmin: 4
  FromSheep: false
    Sheepmax: 2
    Sheepmin: 0
    SheepXPmax: 10
    SheepXPmin: 4
SmeltedOres: false
  SmeltedIron: false
  SmeltedGold: false
GravelAlwaysFlint: false #Make gravel always drop flint.
BatMembranes: false #Allow bats to drop Membranes.
Botancial_Replication_Recipes: false #Put in bonemeal, rotten flesh, and a flower to make 3
ZombieLeatherRecipe: false #Put rotten flesh in a furnace and cook it to make leather!
SnowLayersToBlocks: false #8 Snow Layers in a chest format to a snow block
