name: VooDooPlugin
version: ${project.version}
main: me.lojosho.voodoomasterplugin.Main
api-version: 1.16
authors: [LoJoSho]
description: VooDoo datapacks converted into plugin format all in one plugin.
